version: '3'

services:
  app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    command:
      npm run dev

# WSL2の都合上、node_modulesの同期はDocker volumesで行う
volumes:
  node_modules:
